apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    app: rails-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rails-app
        name: redis
    spec:
      containers:
      - image: redis:3.0.5
        name: redis
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /var/lib/redis/data
          name: drkiq-redis
      restartPolicy: Always
      volumes:
      - name: drkiq-redis
        persistentVolumeClaim:
          claimName: drkiq-redis
